function SleepStagesS2 = importfile_sleep(workbookFile, sheetName, dataLines)
%IMPORTFILE4 Import data from a spreadsheet
%  SLEEPSTAGESS2 = IMPORTFILE4(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  SLEEPSTAGESS2 = IMPORTFILE4(FILE, SHEET) reads from the specified
%  worksheet.
%
%  SLEEPSTAGESS2 = IMPORTFILE4(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  SleepStagesS2 = importfile4("F:\DATA\EEG Data Anne Richards\STAR\Phase 2\Participant 24011\Sleep Stage Report\24011_SleepStages.xls", "Data", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Aug-2025 09:21:16

%% Input handling

% If no sheet is specified, read from Data
if nargin == 1 || isempty(sheetName)
    sheetName = "Data";
end

% If row start and end points are not specified, define defaults
lastRowOfDataIdx = 0;
if nargin <= 2
    dataLines = [3, Inf];
    lastRowOfDataIdx = 1;
elseif dataLines(end,2) >= Inf
    lastRowOfDataIdx = size(dataLines, 1);
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = sheetName;
if lastRowOfDataIdx == 1
    opts.DataRange = "B" + dataLines(1, 1);
else
    opts.DataRange = "B" + dataLines(1, 1) + ":B" + dataLines(1, 2);
end

% Specify column names and types
opts.VariableNames = "VarName2";
opts.VariableTypes = "double";

% Import the data
SleepStagesS2 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    if idx == lastRowOfDataIdx
        opts.DataRange = "B" + dataLines(idx, 1);
    else
        opts.DataRange = "B" + dataLines(idx, 1) + ":B" + dataLines(idx, 2);
    end
    tb = readtable(workbookFile, opts, "UseExcel", false);
    SleepStagesS2 = [SleepStagesS2; tb]; %#ok<AGROW>
end

end