function sleep_scores = load_csv(filename)

% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /media/user/Data/Ana EEG/DDREAMS/DDREAMS_EBE Sleep Stages-selected/20001_1-3_0000334000214_EpochByEpochDetail/20001_20260124_205200____20210809_122452_0000334000214_EpochByEpochDetail.csv
%
% Auto-generated by MATLAB on 03-Sep-2026 22:16:39

% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 56);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Subject_", "Epoch_", "Night", "StudyDate", "ElapsedTime", "ElapsedTime_sec_", "ClockTime", "PrimaryAutoStage", "SecondaryAutoStage", "TechEditStage", "StageFinal", "ChannelStaged", "Sleep_WakeActigraphy", "Spindles", "Cort_MAO", "Snoring_Mean", "Snoring_Min", "Snoring_Max", "x_TimeSnoring", "AutonomicActivations", "Pulse_Mean", "Pulse_Min", "Pulse_Max", "Movement", "SecMov30", "Position", "Delta", "DeltaC", "Theta", "Alpha", "Sigma", "Beta", "EMG", "EMGm", "MeanCorr", "RemEvent30", "x_BadSeconds", "SWsecs", "PhasicREM", "SpDurSec", "NumSDBEvent", "NumSDBEnd", "ImpLEOG", "ImpREOG", "ImpEEG", "ME_1", "ME_2", "ME_3", "ME_4", "ME_5", "ME_6", "ME_7", "ME_8", "ME_9", "ME_10", "Total_ME"];
opts.VariableTypes = ["double", "double", "double", "categorical", "duration", "double", "duration", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["StudyDate", "ChannelStaged", "Position"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "ElapsedTime", "InputFormat", "hh:mm:ss.S");
opts = setvaropts(opts, "ClockTime", "InputFormat", "hh:mm:ss.S");

% Import the data
sleep_scores = readtable(filename, opts);


% Clear temporary variables
clear opts

end